name: jupyterlab-filesystem-docs

channels:
  - conda-forge

dependencies:
  - yarn=1
  - jupyterlab
  - pydata-sphinx-theme
  - jupyter
  - jupyterlite-pyodide-kernel
  - jupyterlite-sphinx
  - pip:
    - ..
